### ISSUE TITLE
Mashup.java의 mashupId 초기화 코드 수정 요청

### ISSUE THREAD

**Issue by hanbandos2** [bluecap-git/lotte-illywa-source#3]
https://github.com/bluecap-git/lotte-illywa-source/blob/1f47d30273825f38a76124cf4f0c522cd01ab12e/illywa-android/app/src/main/java/com/bluecapsystem/lotte/illywa/edl/Mashup.java#L47-L58

51번째 라인과 53번째 라인이 모두 clipId에 값을 대입하고 있습니다. 

51번째 라인이 mashupId가 아닐까 생각되어 수정을 요청드립니다.

**Comment by matin-bcs** [comment]
처리 햇습니다.
