### ISSUE TITLE
EDL 기능에 deleteClip Function이 필요합니다.

### ISSUE THREAD

**Issue by hanbandos2** [bluecap-git/lotte-illywa-source#4]
![image](https://user-images.githubusercontent.com/63337372/83101720-f0734180-a0ed-11ea-85ee-5b83d202ee37.png)

![image](https://user-images.githubusercontent.com/63337372/83101800-1c8ec280-a0ee-11ea-94e1-c847f50fae86.png)

![image](https://user-images.githubusercontent.com/63337372/83101830-2e706580-a0ee-11ea-890e-484dc58ec7da.png)

clip 삭제 기능이 필요합니다.

관련 기능을 추가해주세요.

**Comment by matin-bcs** [comment]
cliplist 에 remove 함수가 있습니다.
